### ISSUE TITLE
Historias de Usuarios

### ISSUE THREAD

**Issue by AngelesMary** [AngelesMary/Proyecto-Full-stack#2]
Plantear Historias de Usuarios y Tareas dependientes de las US.Tener en cuenta la redacción adecuada para las US y nomenclatura, ej “#US01 Como usuario quiero ingresar al carrito para poder comprar”

**Comment by AngelesMary** [comment]
#US01 - Acompañante
Descripción :Como usuario quiero que haya una opción para que pueda jugar con alguien en el caso que no tenga compañero.

**Comment by Garaydiego** [comment]
#US02 - Cotización
 Descripción: Como usuario quiero que la página contenga información sobre el precio y los medios de pago de cada cancha.

#US03 - Servicios extras
Descripción:  Como usuario quiero que muestre una descripción y  fotos de los servicios adicionales que cuenta el club.

#US04 - Cronograma
Descripción: Como usuario quiero poder acceder en forma virtual a los días y horarios de las canchas disponibles.

**Comment by AgustinC98** [comment]
#US05 – Contacto
Descripción: Como usuario quiero ver las formas de contactar al club para obtener el asesoramiento necesario.

#US06 – Ubicación
Descripción: Como usuario quiero ver la localización del club y los medios de transportes cercanos para elegir la mejor opción para ir al club.

**Comment by jona-bustos** [comment]
#US07 - Puntuación
Descripción: Como usuario quiero ver la calificación que tiene el club para ver su reputación.

#US08 - Feedback/Opinión
Descripción: Como usuario quiero calificar al club y poder escribir un comentario para reflejar mi experiencia .

**Comment by saitamaworker** [comment]
#US09 - Descripción de canchas
Descripción: Como usuario quiero saber con qué tipo de característica  cuenta cada cancha.

#US10 - Registro universal
Descripción: Como usuario quiero tener la posibilidad de hacerme socio para poder acceder a todas las instalaciones asociadas al club.

**Comment by veromeme1900** [comment]
#US11- Tienda  
Descripción:  Como usuario quiero la opcion donde me indique varios puntos donde se venda indumentaria y accesorios de padel.

**Comment by Fedemusarra** [comment]
#US12 - Información de torneo
Descripción: Como usuario quiero ver los resultados del dia, fixture/calendario con los próximos partidos para estar actualizado.

**Comment by enzomateo** [comment]
#US13 -  Instalaciones
Descripción: Como usuario quiero ver  aspectos del establecimiento como lugar, baños, canchas, disponibilidad horaria, para su uso.

**Comment by flaqueen** [comment]
#US14 - Torneos
Descripción: Como usuario quiero poder ver e inscribirme en torneos para poder competir con gente de mi nivel.
